Feature/#725 modify type adapter factory spec builder
infinum/jsonapix pull request #15
Opened 2022-04-11 07:54 UTC by gobbletsit

https://app.productive.io/1-infinum/tasks/2547892

This PR contains changes made to simplify getTypeAdapter() usage for non retrofit users with passing either Class<*>.qualifiedName or full ParameterizedType in case of lists.

2022-04-11 08:31 UTC, stjepanbanek requested changes
Good job! I do have 1 suggestion, so please check that out.

2022-04-11 08:31 UTC, stjepanbanek commented on core/src/main/java/com/infinum/jsonapix/core/adapters/AdapterFactory.kt
> +    fun getListAdapter(type: ParameterizedType): TypeAdapter<*>?
This should probably also take the `KClass<*>` as `type` parameter. 
We only need to know about `ParameterizedType` in `JsonXConverterFactory` to determine if we need to call `getAdapter` or `getListAdapter`

2022-04-11 19:34 UTC, gobbletsit commented on core/src/main/java/com/infinum/jsonapix/core/adapters/AdapterFactory.kt
> +    fun getListAdapter(type: ParameterizedType): TypeAdapter<*>?
Are you sure? If so , then you would need to pass a KClass to it from `JsonXConverterFactory.responseBodyConverter` which is basically the same thing as initial implementation and as previous Sting implementation which doesn't solve the issue.

2022-04-11 19:39 UTC, gobbletsit commented on core/src/main/java/com/infinum/jsonapix/core/adapters/AdapterFactory.kt
> +    fun getListAdapter(type: ParameterizedType): TypeAdapter<*>?
In that case, you will not be able to pull argument types qualified name from KClass like you can from ParameterizedType.

`(type.actualTypeArguments.first() as Class<*>).kotlin.qualifiedName`

2022-04-11 20:13 UTC, gobbletsit commented on core/src/main/java/com/infinum/jsonapix/core/adapters/AdapterFactory.kt
> +    fun getListAdapter(type: ParameterizedType): TypeAdapter<*>?
We can only do it like this if you prefer but then we just moved it from SpecBuilder to here.

`adapterFactory.getListAdapter((type.actualTypeArguments.first() as Class<*>).kotlin)?.let {
                    JsonXResponseBodyConverter(it)
  }`

2022-04-13 13:51 UTC, stjepanbanek approved these changes

2022-04-13 13:51 UTC, merged